<?php
/*
 ''=>[
            'type'=>'',
            'name'=>'',
            'c_name'=>''
        ],

''=>[
            'ckey'=>'',
            'c_name'=>'',
        ],
 * */
return [
    //订单列表
  'list'=>[
      //查询字段配置
    'query'=>[
        '0'=>[
            //form类型
            'type'=>'select',
            //form 名字
            'name'=>'order_type',
            //中文
            'c_name'=>'订单类型'
        ],
        '1'=>[
            'type'=>'text',
            'name'=>'oc_number',
            'c_name'=>'卡号'
        ],
        '2'=>[
            'type'=>'select',
            'name'=>'province',
            'c_name'=>'省份'
        ],
        '3'=>[
            'type'=>'text',
            'name'=>'name',
            'c_name'=>'姓名'
        ],
        '4'=>[
            'type'=>'text',
            'name'=>'number',
            'c_name'=>'编号'
        ],
        '5'=>[
            'type'=>'submit',
            'name'=>'submit',
            'c_name'=>'提交'
        ]

    ],
      //数据表配置
    'panel'=>[
        '0'=>[
            //对应字段
            'ckey'=>'number',
            //中文
            'c_name'=>'订单号',
        ],
        '1'=>[
            'ckey'=>'oc_number',
            'c_name'=>'油卡信息',
        ],
        '2'=>[
            'ckey'=>'updated_at',
            'c_name'=>'修改时间',
        ],
        '3'=>[
            'ckey'=>'number_status',
            'c_name'=>'订单状态',
        ],
        '4'=>[
            'ckey'=>'img_id',
            'c_name'=>'查看截图',
        ],
    ],
  ],
  'camilo'=>[
      'query'=>[
          '0'=>[
              'type'=>'select',
              'name'=>'status',
              'c_name'=>'卡密状态'
          ],
          '1'=>[
              'type'=>'text',
              'name'=>'commodity',
              'c_name'=>'商品'
          ],
          '2'=>[
              'type'=>'text',
              'name'=>'',
              'c_name'=>'订单号'
          ],
          '3'=>[
              'type'=>'text',
              'name'=>'',
              'c_name'=>'卡号'
          ],
          '4'=>[
              'type'=>'select',
              'name'=>'denomination',
              'c_name'=>'面额'
          ],
          '5'=>[
              'type'=>'text',
              'name'=>'trading_time',
              'c_name'=>'交易时间'
          ],
          '6'=>[
              'type'=>'submit',
              'name'=>'submit',
              'c_name'=>'提交'
          ],
      ],
      'panel'=>[
          '0'=>[
              'ckey'=>'',
              'c_name'=>'订单号',
          ],
          '1'=>[
              'ckey'=>'',
              'c_name'=>'商品',
          ],
          '2'=>[
              'ckey'=>'',
              'c_name'=>'面额',
          ],
          '3'=>[
              'ckey'=>'',
              'c_name'=>'交易时间',
          ],
          '4'=>[
              'ckey'=>'',
              'c_name'=>'卡号',
          ],
          '5'=>[
              'ckey'=>'',
              'c_name'=>'密码',
          ],
          '6'=>[
              'ckey'=>'',
              'c_name'=>'卡密状态',
          ],
          '7'=>[
              'ckey'=>'',
              'c_name'=>'价格',
          ],
      ],
  ],
  'camilorecharge'=>[
      'query'=>[],
      'panel'=>[],
  ],
    //直冲订单订购
  'directlyrecharge'=>[
      'query'=>[
          '0'=>[
              'type'=>'select',
              'name'=>'procurement_type',
              'c_name'=>'采购方式'
          ],
          '1'=>[
              'type'=>'select',
              'name'=>'discount',
              'c_name'=>'折扣'
          ],
          '2'=>[
              'type'=>'text',
              'name'=>'end_time',
              'c_name'=>'截止时间'
          ],
          '3'=>[
              'type'=>'text',
              'name'=>'num',
              'c_name'=>'采购数量'
          ],
          '4'=>[
              'type'=>'select',
              'name'=>'oil_card',
              'c_name'=>'选择油卡'
          ],
      ],
      'panel'=>[
          '0'=>[
              'ckey'=>'oc_number',
              'c_name'=>'编号',
          ],
          '1'=>[
              'ckey'=>'name',
              'c_name'=>'姓名',
          ],
          '2'=>[
              'ckey'=>'card_number',
              'c_name'=>'油卡',
          ],
          '3'=>[
              'ckey'=>'number_status',
              'c_name'=>'状态',
          ],
      ],
    ],
  'oilcardbinding'=>[
      'query'=>[],
      'panel'=>[],
    ],
  'usermessage'=>[
      'query'=>[],
      'panel'=>[],
    ],
  'message'=>[
      'query'=>[],
      'panel'=>[],
    ],
];