<?php
/*
 ''=>[
            'type'=>'',
            'name'=>'',
            'c_name'=>''
        ],
 * */
return [
  'list'=>[
    'query'=>[
        '0'=>[
            'type'=>'select',
            'name'=>'order_type',
            'c_name'=>'订单类型'
        ],
        '1'=>[
            'type'=>'text',
            'name'=>'oc_number',
            'c_name'=>'卡号'
        ],
        '2'=>[
            'type'=>'select',
            'name'=>'province',
            'c_name'=>'省份'
        ],
        '3'=>[
            'type'=>'text',
            'name'=>'name',
            'c_name'=>'姓名'
        ],
        '4'=>[
            'type'=>'text',
            'name'=>'number',
            'c_name'=>'编号'
        ],
        '5'=>[
            'type'=>'submit',
            'name'=>'submit',
            'c_name'=>'提交'
        ]

    ],
    'panel'=>[
        '0'=>[
            'ckey'=>'number',
            'c_name'=>'订单号',
        ],
        '1'=>[
            'ckey'=>'oc_number',
            'c_name'=>'油卡信息',
        ],
        '2'=>[
            'ckey'=>'updated_at',
            'c_name'=>'修改时间',
        ],
        '3'=>[
            'ckey'=>'number_status',
            'c_name'=>'订单状态',
        ],
        '4'=>[
            'ckey'=>'img_id',
            'c_name'=>'查看截图',
        ],
    ],
  ],
  'camilo'=>[
      'query'=>[],
      'panel'=>[],
  ],
  'camilorecharge'=>[
      'query'=>[],
      'panel'=>[],
  ],
  'directlyrecharge'=>[
      'query'=>[],
      'panel'=>[],
    ],
  'oilcardbinding'=>[
      'query'=>[],
      'panel'=>[],
    ],
  'usermessage'=>[
      'query'=>[],
      'panel'=>[],
    ],
  'message'=>[
      'query'=>[],
      'panel'=>[],
    ],
];